Change use sock recommended
yuki-yano/zeno.zsh pull request #72
Opened 2023-02-04 08:51 UTC by yuki-yano

2023-02-08 06:25 UTC, Milly requested changes

2023-02-08 06:25 UTC, Milly commented on README.md
> +# export ZENO_ENABLE_SOCK=0
I suggest changing the variable.
Expecting default values to be empty is a good design for zero configuration.

```suggestion
# by default a unix domain socket is used
# if disable it
# export ZENO_DISABLE_SOCK=1
```

Also change the line in file *shell/function/zeno-call-client-and-fallback*.

```diff
--- a/shell/function/zeno-call-client-and-fallback
+++ b/shell/function/zeno-call-client-and-fallback
@@ -1,6 +1,6 @@
 #autoload
 
-if [[ -n $ZENO_ENABLE_SOCK ]]; then
+if [[ -z $ZENO_DISABLE_SOCK ]]; then
   (( $+functions[zeno-client] )) || zeno-enable-sock
   if [[ -S $ZENO_SOCK ]]; then
     zeno-client "$@"
```

2023-02-08 06:25 UTC, Milly commented on shell/function/zeno-enable-sock
> -export ZENO_ENABLE_SOCK=1
Changing variable.

```suggestion
unset ZENO_DISABLE_SOCK
```

2023-02-08 06:25 UTC, Milly commented on zeno.zsh
> +if [[ $ZENO_ENABLE_SOCK == "1" ]]; then
Changing variable.

```suggestion
if [[ -z $ZENO_DISABLE_SOCK ]]; then
```

Also change the following line:

```diff
   else
-    unset ZENO_ENABLE_SOCK
+    export ZENO_DISABLE_SOCK=1
   fi
```

2025-06-24 07:55 UTC, yuki-yano commented
@Milly さんのレビューコメントに基づいて、以下の修正を行いました：

## 変更内容

1. **変数名の変更**: `ZENO_ENABLE_SOCK` → `ZENO_DISABLE_SOCK`
   - ソケット機能がデフォルトで有効になり、無効化したい場合のみ `export ZENO_DISABLE_SOCK=1` を設定する仕様に変更
   - ゼロコンフィギュレーションの設計原則に従った実装

2. **mainブランチとのコンフリクト解消**
   - 最新のmainブランチ（50コミット分）をマージ
   - Fish shell対応やディレクトリ構造の変更に対応

3. **ZshとFishの動作統一**
   - 両シェルで`ZENO_DISABLE_SOCK=""`（空文字列）の場合はソケットが有効になるよう修正
   - エッジケースの動作を確認し、一貫性を保証

4. **ドキュメント更新**
   - README.mdとCLAUDE.mdの古い変数名参照を更新

全てのテストが成功し、型チェックも通過しています。

2025-06-24 07:55 UTC, yuki-yano commented
Based on @Milly's review comments, I've made the following changes:

## Changes

1. **Variable name change**: `ZENO_ENABLE_SOCK` → `ZENO_DISABLE_SOCK`
   - Socket functionality is now enabled by default
   - Users only need to set `export ZENO_DISABLE_SOCK=1` to disable it
   - Follows zero-configuration design principles

2. **Resolved conflicts with main branch**
   - Merged latest main branch (50 commits)
   - Adapted to Fish shell support and directory structure changes

3. **Unified behavior between Zsh and Fish**
   - Fixed Fish implementation to handle `ZENO_DISABLE_SOCK=""` (empty string) correctly
   - Both shells now treat empty string as socket enabled
   - Verified edge case behavior for consistency

4. **Updated documentation**
   - Updated old variable name references in README.md and CLAUDE.md

All tests pass and type checking succeeds.

2025-06-24 07:56 UTC, merged